modLoader="javafml"
loaderVersion="[38,)"
license="LGPL-3.0"
issueTrackerURL="https://github.com/Janoeo/DiaboloLib/issues"
[[mods]]
modId="diolib"
version="${file.jarVersion}"
displayName="Diabolo Lib"
logoFile="diabolo-lib.png"
authors="AlasDiablo, lIotaMiu & Safyrus"
description='''
Libray Mod for Janoeo Project and more !
'''
[[dependencies.diolib]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.diolib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
