modLoader = "javafml"
loaderVersion = "[46,)"
license = "LGPL-3.0 License"
issueTrackerURL = "https://github.com/Janoeo/DiaboloLib/issues"

[[mods]]
    modId = "diolib"
    version = "${file.jarVersion}"
    displayName = "DiaboloLib"
    displayURL = "https://github.com/Janoeo/DiaboloLib"
    authors = "AlasDiablo & Safyrus"
    description = '''
    Libray Mod for Janoeo Project and more !
    '''

[[dependencies.diolib]]
    modId = "forge"
    mandatory = true
    versionRange = "[46,)"
    ordering = "NONE"
    side = "BOTH"
[[dependencies.diolib]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.20,1.21)"
    ordering = "NONE"
    side = "BOTH"
